jardin_homepage:
    path:     /
    defaults: { _controller: JardinBundle:Default:index }

parent_home:
    path:       /parent-home
    defaults:   {_controller: JardinBundle:Main:parentHome }

dashboard_home:
    path:       /dashboard
    defaults:   {_controller: JardinBundle:Main:dashboardHome }

enseignant_home:
    path:       /enseignant-home
    defaults: {_controller: JardinBundle:Main:enseignantHome}
evenement_feature:
    resource: "@JardinBundle/Resources/config/routing/evenement.yml"
    prefix:   /dashboard/events



