jardin_homepage:
    path:     /
    defaults: { _controller: JardinBundle:Default:index }

parent_home:
    path:       /parent-home
    defaults:   {_controller: JardinBundle:Main:parentHome }

dashboard_home:
    path:       /dashboard
    defaults:   {_controller: JardinBundle:Main:dashboardHome }

enseignant_home:
    path:       /enseignant-home
    defaults: {_controller: JardinBundle:Main:enseignantHome}

evenement_dashboard:
    resource: "@JardinBundle/Resources/config/routing/evenement.yml"
    prefix:   /dashboard/events

parent_evenements:
    path:       /parent/evenements
    defaults: {_controller: JardinBundle:Evenement:listEvenementParent}

inscription_evenements:
    path:       /parent/inscription/{idEvenement}
    defaults: {_controller: JardinBundle:InscriptionEvenement:inscrireEvenement}

desinscription_evenements:
    path:       /parent/deinscription/{idEvenement}
    defaults: {_controller: JardinBundle:InscriptionEvenement:annulerInscription}


